Rails.application.routes.draw do

  get 'jokes/random' => 'jokes#random'
  get '/sessions/destroy' => 'sessions#destroy'
  get '/sessions/create' => 'sessions#create'
  get '/sessions/new' => 'sessions#new'
  get '/home' => 'application#home'
  get '/new_joke' => 'jokes#new'
  get '/create_joke' => 'jokes#create'
  get '/jokes' => 'jokes#index'
  get '/jokes/:id' => 'jokes#show'
  get '/jokes/:id/edit' => 'jokes#edit'
  get '/jokes/:id/update' => 'jokes#update'
  get '/jokes/:id/destroy' => 'jokes#destroy'
  get '/new_rating' => 'ratings#new'
  get '/create_rating' => 'ratings#create'
  get '/ratings' => 'ratings#index'
  get '/ratings/:id' => 'ratings#show'
  get '/ratings/:id/edit' => 'ratings#edit'
  get '/ratings/:id/update' => 'ratings#update'
  get '/ratings/:id/destroy' => 'ratings#destroy'
  get '/new_user' => 'users#new'
  get '/create_user' => 'users#create'
  get '/users' => 'users#index'
  get '/users/:id' => 'users#show'
  get '/users/:id/edit' => 'users#edit'
  get '/users/:id/update' => 'users#update'
  get '/users/:id/destroy' => 'users#destroy'

end
